# Generated by Django 3.0.7 on 2020-07-03 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(default=None, max_length=10)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, default='Noida', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('postal_code', models.IntegerField(blank=True, default=None, null=True)),
                ('age', models.IntegerField(default=20, null=True)),
                ('gender', models.CharField(default='Male', max_length=10, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('additional_information', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default=None, upload_to='Accounts')),
                ('shop_name', models.CharField(blank=True, default=None, max_length=100)),
                ('shop_GST_no', models.CharField(blank=True, default=None, max_length=100)),
                ('aadhar_card_no', models.CharField(blank=True, default=None, max_length=100)),
                ('aadhar_pic', models.ImageField(blank=True, default=None, upload_to='Accounts')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None, max_length=300)),
                ('category', models.CharField(default=None, max_length=100)),
                ('brand', models.CharField(default=None, max_length=100)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('quantity', models.IntegerField(default=None)),
                ('stock', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('color', models.CharField(blank=True, default=None, max_length=100)),
                ('return_policy', models.CharField(blank=True, default=None, max_length=100)),
                ('delivery_charge', models.IntegerField(blank=True, default=None, null=True)),
                ('main_photo', models.ImageField(blank=True, upload_to='products')),
                ('optional_photo1', models.ImageField(blank=True, upload_to='products')),
                ('optional_photo2', models.ImageField(blank=True, upload_to='products')),
                ('optional_photo3', models.ImageField(blank=True, upload_to='products')),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Seller')),
            ],
            options={
                'permissions': (('edit_product', 'Can add product'),),
            },
        ),
    ]
