# Generated by Django 3.0.7 on 2020-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='aadhar_card_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='aadhar_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Accounts'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_GST_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
