# Generated by Django 3.0.7 on 2020-07-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200703_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Terms_conditions',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='in_offer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
