# Generated by Django 3.0.7 on 2020-07-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_in_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Terms_conditions',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, max_length=3000),
        ),
    ]
