# Generated by Django 3.0.7 on 2020-07-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_on',
        ),
    ]
