# Generated by Django 3.0.7 on 2020-07-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200706_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_description',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Terms_conditions',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
