# Generated by Django 3.0.7 on 2020-07-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200706_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_charge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
