# Generated by Django 3.0.7 on 2020-07-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Terms_conditions',
            field=models.CharField(blank=True, default=None, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, max_length=300000),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_description',
            field=models.TextField(blank=True, default=None, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='additional_information',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
